# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MashKensyu' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MashKensyu

  target 'MashKensyuTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MashKensyuUITests' do
    # Pods for testing
  end
  pod 'RealmSwift'
end
